# Notes:
# - Minimal appveyor.yml file is an empty file. All sections are optional.
# - Indent each level of configuration with 2 spaces. Do not use tabs!
# - All section names are case-sensitive.
# - Section names should be unique on each level.

#---------------------------------#
#  general configuration          #
#---------------------------------#

# version format
version: '{branch}-{build}'

# Do not build on tags (GitHub only)
skip_tags: true

# avoid malicious attempt via pull requests
branches:
  only:
    - master


#---------------------------------#
#  environment configuration      #
#---------------------------------#

# environment variables
# build system info: https://www.appveyor.com/docs/build-environment/#pre-installed-software
os: Visual Studio 2017

environment:
  REPO_DIR: &REPO_DIR c:\project  # directory created by appveyor

  SOL_FILE: foo_uie_dsp_switcher.sln
  MSBUILD_CMD: /m /p:Configuration=Release

# clone directory
clone_folder: *REPO_DIR


#---------------------------------#
#  build configuration            #
#---------------------------------#

# scripts to run before build
before_build:
  # git submodules
  - 'cd "%REPO_DIR%"'
  - 'git submodule update --init --remote --depth 1 --recursive'

# to run your custom scripts instead of automatic MSBuild
build_script:
  - 'cd "%REPO_DIR%"'
  - 'msbuild %SOL_FILE% %MSBUILD_CMD%'

# scripts to run before deployment
after_build:
  # prepare for artifacts packaging
  - 'cd "%REPO_DIR%"'
  - 'copy "%REPO_DIR%\Release\foo_uie_dsp_switcher.dll" "%REPO_DIR%"'  # the artifact must reside at the source repo root
  - '7z a -tzip -mx9 "foo_uie_dsp_switcher.fb2k-component" "foo_uie_dsp_switcher.dll"'
  - 'powershell -Command "& { (Get-FileHash -Algorithm SHA1 "foo_uie_dsp_switcher.fb2k-component").hash; }" > "foo_uie_dsp_switcher.fb2k-component.sha1"'


#---------------------------------#
#  tests configuration            #
#---------------------------------#

# to disable automatic tests
test: off


#---------------------------------#
#  artifacts configuration        #
#---------------------------------#

artifacts:
  - path: foo_uie_dsp_switcher.fb2k-component
    name: plugin
  - path: foo_uie_dsp_switcher.fb2k-component.sha1
    name: checksum
